// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://example.org/StructureDefinition/IncomingHL7v2Message
export interface IncomingHL7v2Message extends DomainResource {
    resourceType: "IncomingHL7v2Message";

    bundle?: string;
    date?: string;
    error?: string;
    message: string;
    patient?: Reference<"Patient">;
    sendingApplication?: string;
    sendingFacility?: string;
    status?: string;
    type: string;
}
export const isIncomingHL7v2Message = (resource: unknown): resource is IncomingHL7v2Message => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "IncomingHL7v2Message";
}
