// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://example.org/StructureDefinition/OutgoingBarMessage
export interface OutgoingBarMessage extends DomainResource {
    resourceType: "OutgoingBarMessage";

    hl7v2?: string;
    invoice: Reference<"Invoice">;
    patient: Reference<"Patient">;
    status: string;
}
export const isOutgoingBarMessage = (resource: unknown): resource is OutgoingBarMessage => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "OutgoingBarMessage";
}
