/**
 * Parsed domain model for IncomingHL7v2Message — Elm-style sound typing.
 *
 * WHY THIS EXISTS
 * ---------------
 * The wire type (`src/fhir/aidbox-hl7v2-custom/IncomingHl7v2message.ts`) is
 * autogenerated from the FHIR profile and, by FHIR convention, has every
 * discriminating field optional:
 *   status? unmappedCodes? entries? error?
 *
 * That means the compiler happily accepts nonsense like
 *   { status: "processed", error: "oops" }                // impossible IRL
 *   { status: "code_mapping_error", unmappedCodes: undefined }
 *
 * And every reader has to defend against it with `?.` and fallback arms for
 * states that don't exist.
 *
 * This module applies "parse, don't validate": the wire type stays permissive
 * at the boundary, but one call to `parseIncomingMessage` narrows it into
 * `ParsedIncomingMessage` — a tagged union where each variant carries exactly
 * the fields its status guarantees. Downstream readers switch on `kind` and
 * the compiler enforces that every arm only touches fields that are actually
 * present.
 *
 * `assertNever` makes the exhaustiveness check load-bearing: if a new status
 * is added, every switch that forgot to handle it fails to typecheck.
 */

import type {
  IncomingHL7v2Message as WireMessage,
  UnmappedCode,
} from "../../fhir/aidbox-hl7v2-custom";
import type { DomainResource } from "../../fhir/hl7-fhir-r4-core/DomainResource";

// ============================================================================
// Branded MessageId
// ============================================================================

/**
 * A `string` that TypeScript treats nominally. Plain strings can't be
 * assigned to a `MessageId` parameter — they have to go through
 * `toMessageId()`. This eliminates the "oops I passed a ConceptMap id
 * where a message id was expected" class of bug.
 */
export type MessageId = string & { readonly __brand: "MessageId" };

export function toMessageId(s: string): MessageId {
  return s as MessageId;
}

// ============================================================================
// Parsed tagged union
// ============================================================================

/** Fields every parsed message carries regardless of status. */
export interface IncomingMessageBase {
  id: MessageId;
  type: string;
  date: string;
  sendingApplication: string;
  /** Optional on the wire; fall back to id or em-dash in display code. */
  messageControlId?: string;
  /** Optional on the wire; only combined with sendingApplication for display. */
  sendingFacility?: string;
  lastUpdated: string;
  rawMessage: string;
}

/**
 * Tagged union — each variant carries exactly the fields its status
 * guarantees. Construction of an impossible combination (e.g. a
 * `processed` variant with an `error`) is a compile-time error.
 */
export type ParsedIncomingMessage = IncomingMessageBase & (
  | { kind: "received" }
  | { kind: "deferred"; note?: string }
  | { kind: "parsing_error"; error: string }
  | { kind: "conversion_error"; error: string }
  | { kind: "sending_error"; error: string }
  | { kind: "code_mapping_error"; unmappedCodes: readonly UnmappedCode[] }
  | { kind: "processed"; entries: readonly DomainResource[] }
  | { kind: "warning"; entries: readonly DomainResource[]; error: string }
);

// ============================================================================
// Malformed records
// ============================================================================

/**
 * Returned by `parseIncomingMessage` when the wire record is missing
 * mandatory domain fields (e.g. no id, no type, or a status that needs
 * payload fields but doesn't have them). These are dropped from list
 * views with a logged warning rather than crashing the page.
 */
interface MalformedWireRecord {
  kind: "malformed-wire-record";
  wireId: string | undefined;
  reason: string;
}

export function isMalformed(
  x: ParsedIncomingMessage | MalformedWireRecord,
): x is MalformedWireRecord {
  return x.kind === "malformed-wire-record";
}

// ============================================================================
// Boundary parser — "parse, don't validate"
// ============================================================================

/**
 * Convert the permissive wire type into the narrow domain type. Called
 * once at the read boundary (list fetch, single-message fetch, history
 * version resolver). All downstream code consumes the parsed result.
 *
 * Returns `MalformedWireRecord` if the wire record can't be cleanly
 * classified — callers typically log and skip those.
 */
export function parseIncomingMessage(
  raw: WireMessage,
): ParsedIncomingMessage | MalformedWireRecord {
  const wireId = raw.id;

  // Mandatory common fields
  if (!wireId) {
    return {
      kind: "malformed-wire-record",
      wireId: undefined,
      reason: "wire record has no id",
    };
  }
  if (!raw.type) {
    return {
      kind: "malformed-wire-record",
      wireId,
      reason: "wire record has no type",
    };
  }
  // `message` (raw HL7v2) is required on the wire schema but Aidbox has
  // been observed to strip it on partial projections (`_elements=`). Fall
  // back to empty-string rather than malformed-drop the row — losing raw
  // HL7v2 shouldn't hide a message from the list.
  const rawMessage = raw.message ?? "";
  const lastUpdated = raw.meta?.lastUpdated ?? "";
  const date = raw.date ?? lastUpdated;
  const sendingApplication = raw.sendingApplication ?? "—";

  const base: IncomingMessageBase = {
    id: toMessageId(wireId),
    type: raw.type,
    date,
    sendingApplication,
    ...(raw.messageControlId !== undefined ? { messageControlId: raw.messageControlId } : {}),
    ...(raw.sendingFacility !== undefined ? { sendingFacility: raw.sendingFacility } : {}),
    lastUpdated,
    rawMessage,
  };

  // Absent status → "received". Matches the worker semantics: a message
  // with no status is one we've ingested but haven't classified yet.
  const status = raw.status ?? "received";

  switch (status) {
    case "received":
      return { ...base, kind: "received" };

    case "deferred":
      return raw.error
        ? { ...base, kind: "deferred", note: raw.error }
        : { ...base, kind: "deferred" };

    case "parsing_error":
      return {
        ...base,
        kind: "parsing_error",
        error: raw.error ?? "parse failed",
      };

    case "conversion_error":
      return {
        ...base,
        kind: "conversion_error",
        error: raw.error ?? "conversion failed",
      };

    case "sending_error":
      return {
        ...base,
        kind: "sending_error",
        error: raw.error ?? "submit to Aidbox failed",
      };

    case "code_mapping_error": {
      const codes = raw.unmappedCodes ?? [];
      if (codes.length === 0) {
        return {
          kind: "malformed-wire-record",
          wireId,
          reason: "code_mapping_error with no unmappedCodes",
        };
      }
      return { ...base, kind: "code_mapping_error", unmappedCodes: codes };
    }

    case "processed":
      return {
        ...base,
        kind: "processed",
        entries: raw.entries ?? [],
      };

    case "warning":
      return {
        ...base,
        kind: "warning",
        entries: raw.entries ?? [],
        error: raw.error ?? "warning without explanation",
      };

    default: {
      // status is narrowed to `never` here if we've handled every
      // case above. If Aidbox ships a new status value the wire type
      // knows about, this compiles but fails at runtime — caught by
      // the exhaustiveness assertion below.
      const _exhaustive: never = status;
      return {
        kind: "malformed-wire-record",
        wireId,
        reason: `unknown status: ${JSON.stringify(_exhaustive)}`,
      };
    }
  }
}

/**
 * Parse a wire bundle's messages, dropping and logging malformed
 * records. Returns only the successfully parsed variants — callers
 * never see malformed records.
 */
export function parseIncomingMessages(
  rawMessages: readonly WireMessage[],
): ParsedIncomingMessage[] {
  const parsed: ParsedIncomingMessage[] = [];
  for (const raw of rawMessages) {
    const result = parseIncomingMessage(raw);
    if (isMalformed(result)) {
      console.warn(
        `[incoming-message] dropping malformed record (id=${result.wireId ?? "?"}): ${result.reason}`,
      );
      continue;
    }
    parsed.push(result);
  }
  return parsed;
}

// ============================================================================
// Exhaustiveness helper
// ============================================================================

/**
 * Compiler-enforced exhaustiveness checker. Place at the `default:`
 * arm of a `switch (x.kind)`; if any variant is unhandled, `x` won't
 * have narrowed to `never` and typecheck fails.
 *
 *   switch (p.kind) {
 *     case "received":  ...
 *     case "processed": ...
 *     // forgetting a case → `p` is not `never` → compile error
 *     default: return assertNever(p);
 *   }
 */
export function assertNever(x: never): never {
  throw new Error(
    `assertNever: unhandled variant ${JSON.stringify(x)}`,
  );
}
