// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Money } from "../hl7-fhir-r4-core/Money";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Money } from "../hl7-fhir-r4-core/Money";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface ChargeItemDefinitionApplicability extends BackboneElement {
    description?: string;
    expression?: string;
    language?: string;
}

export interface ChargeItemDefinitionPropertyGroup extends BackboneElement {
    applicability?: ChargeItemDefinitionApplicability[];
    priceComponent?: ChargeItemDefinitionPropertyGroupPriceComponent[];
}

export interface ChargeItemDefinitionPropertyGroupPriceComponent extends BackboneElement {
    amount?: Money;
    code?: CodeableConcept;
    factor?: number;
    type: ("base" | "surcharge" | "deduction" | "discount" | "tax" | "informational");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ChargeItemDefinition
export interface ChargeItemDefinition extends DomainResource {
    resourceType: "ChargeItemDefinition";

    applicability?: ChargeItemDefinitionApplicability[];
    approvalDate?: string;
    code?: CodeableConcept;
    contact?: ContactDetail[];
    copyright?: string;
    date?: string;
    derivedFromUri?: string[];
    description?: string;
    effectivePeriod?: Period;
    experimental?: boolean;
    identifier?: Identifier[];
    instance?: Reference<"Device" | "Medication" | "Substance">[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    partOf?: string[];
    propertyGroup?: ChargeItemDefinitionPropertyGroup[];
    publisher?: string;
    replaces?: string[];
    status: ("draft" | "active" | "retired" | "unknown");
    title?: string;
    url: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isChargeItemDefinition = (resource: unknown): resource is ChargeItemDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ChargeItemDefinition";
}
