// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface CommunicationPayload extends BackboneElement {
    contentAttachment?: Attachment;
    contentReference?: Reference<"Resource">;
    contentString?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Communication
export interface Communication extends DomainResource {
    resourceType: "Communication";

    about?: Reference<"Resource">[];
    basedOn?: Reference<"Resource">[];
    category?: CodeableConcept[];
    encounter?: Reference<"Encounter">;
    identifier?: Identifier[];
    inResponseTo?: Reference<"Communication">[];
    instantiatesCanonical?: string[];
    instantiatesUri?: string[];
    medium?: CodeableConcept[];
    note?: Annotation[];
    partOf?: Reference<"Resource">[];
    payload?: CommunicationPayload[];
    priority?: ("routine" | "urgent" | "asap" | "stat");
    reasonCode?: CodeableConcept[];
    reasonReference?: Reference<"Condition" | "DiagnosticReport" | "DocumentReference" | "Observation">[];
    received?: string;
    recipient?: Reference<"CareTeam" | "Device" | "Group" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">[];
    sender?: Reference<"Device" | "HealthcareService" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    sent?: string;
    status: ("preparation" | "in-progress" | "not-done" | "on-hold" | "stopped" | "completed" | "entered-in-error" | "unknown");
    statusReason?: CodeableConcept;
    subject?: Reference<"Group" | "Patient">;
    topic?: CodeableConcept;
}
export const isCommunication = (resource: unknown): resource is Communication => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Communication";
}
