// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface ConceptMapGroup extends BackboneElement {
    element: ConceptMapGroupElement[];
    source?: string;
    sourceVersion?: string;
    target?: string;
    targetVersion?: string;
    unmapped?: ConceptMapGroupUnmapped;
}

export interface ConceptMapGroupElement extends BackboneElement {
    code?: string;
    display?: string;
    target?: ConceptMapGroupElementTarget[];
}

export interface ConceptMapGroupElementTarget extends BackboneElement {
    code?: string;
    comment?: string;
    dependsOn?: ConceptMapGroupElementTargetDependsOn[];
    display?: string;
    equivalence: ("relatedto" | "equivalent" | "equal" | "wider" | "subsumes" | "narrower" | "specializes" | "inexact" | "unmatched" | "disjoint");
    product?: ConceptMapGroupElementTargetDependsOn[];
}

export interface ConceptMapGroupElementTargetDependsOn extends BackboneElement {
    display?: string;
    property: string;
    system?: string;
    value: string;
}

export interface ConceptMapGroupUnmapped extends BackboneElement {
    code?: string;
    display?: string;
    mode: ("provided" | "fixed" | "other-map");
    url?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ConceptMap
export interface ConceptMap extends DomainResource {
    resourceType: "ConceptMap";

    contact?: ContactDetail[];
    copyright?: string;
    date?: string;
    description?: string;
    experimental?: boolean;
    group?: ConceptMapGroup[];
    identifier?: Identifier;
    jurisdiction?: CodeableConcept[];
    name?: string;
    publisher?: string;
    purpose?: string;
    sourceCanonical?: string;
    sourceUri?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    targetCanonical?: string;
    targetUri?: string;
    title?: string;
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isConceptMap = (resource: unknown): resource is ConceptMap => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ConceptMap";
}
