// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Quantity } from "../hl7-fhir-r4-core/Quantity";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactPoint } from "../hl7-fhir-r4-core/ContactPoint";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Quantity } from "../hl7-fhir-r4-core/Quantity";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

export interface DeviceDeviceName extends BackboneElement {
    name: string;
    type: ("udi-label-name" | "user-friendly-name" | "patient-reported-name" | "manufacturer-name" | "model-name" | "other");
}

export interface DeviceProperty extends BackboneElement {
    type: CodeableConcept;
    valueCode?: CodeableConcept[];
    valueQuantity?: Quantity[];
}

export interface DeviceSpecialization extends BackboneElement {
    systemType: CodeableConcept;
    version?: string;
}

export interface DeviceUdiCarrier extends BackboneElement {
    carrierAIDC?: string;
    carrierHRF?: string;
    deviceIdentifier?: string;
    entryType?: ("barcode" | "rfid" | "manual" | "card" | "self-reported" | "unknown");
    issuer?: string;
    jurisdiction?: string;
}

export interface DeviceVersion extends BackboneElement {
    component?: Identifier;
    type?: CodeableConcept;
    value: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Device
export interface Device extends DomainResource {
    resourceType: "Device";

    contact?: ContactPoint[];
    definition?: Reference<"DeviceDefinition">;
    deviceName?: DeviceDeviceName[];
    distinctIdentifier?: string;
    expirationDate?: string;
    identifier?: Identifier[];
    location?: Reference<"Location">;
    lotNumber?: string;
    manufactureDate?: string;
    manufacturer?: string;
    modelNumber?: string;
    note?: Annotation[];
    owner?: Reference<"Organization">;
    parent?: Reference<"Device">;
    partNumber?: string;
    patient?: Reference<"Patient">;
    property?: DeviceProperty[];
    safety?: CodeableConcept[];
    serialNumber?: string;
    specialization?: DeviceSpecialization[];
    status?: ("active" | "inactive" | "entered-in-error" | "unknown");
    statusReason?: CodeableConcept[];
    type?: CodeableConcept;
    udiCarrier?: DeviceUdiCarrier[];
    url?: string;
    version?: DeviceVersion[];
}
export const isDevice = (resource: unknown): resource is Device => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Device";
}
