// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/EnrollmentResponse
export interface EnrollmentResponse extends DomainResource {
    resourceType: "EnrollmentResponse";

    created?: string;
    disposition?: string;
    identifier?: Identifier[];
    organization?: Reference<"Organization">;
    outcome?: ("queued" | "complete" | "error" | "partial");
    request?: Reference<"EnrollmentRequest">;
    requestProvider?: Reference<"Organization" | "Practitioner" | "PractitionerRole">;
    status?: ("active" | "cancelled" | "draft" | "entered-in-error");
}
export const isEnrollmentResponse = (resource: unknown): resource is EnrollmentResponse => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "EnrollmentResponse";
}
