// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Duration } from "../hl7-fhir-r4-core/Duration";
import type { Expression } from "../hl7-fhir-r4-core/Expression";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { Timing } from "../hl7-fhir-r4-core/Timing";
import type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
export type { Duration } from "../hl7-fhir-r4-core/Duration";
export type { Expression } from "../hl7-fhir-r4-core/Expression";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { Timing } from "../hl7-fhir-r4-core/Timing";
export type { TriggerDefinition } from "../hl7-fhir-r4-core/TriggerDefinition";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface EvidenceVariableCharacteristic extends BackboneElement {
    definitionCanonical?: string;
    definitionCodeableConcept?: CodeableConcept;
    definitionDataRequirement?: DataRequirement;
    definitionExpression?: Expression;
    definitionReference?: Reference<"Group">;
    definitionTriggerDefinition?: TriggerDefinition;
    description?: string;
    exclude?: boolean;
    groupMeasure?: ("mean" | "median" | "mean-of-mean" | "mean-of-median" | "median-of-mean" | "median-of-median");
    participantEffectiveDateTime?: string;
    participantEffectiveDuration?: Duration;
    participantEffectivePeriod?: Period;
    participantEffectiveTiming?: Timing;
    timeFromStart?: Duration;
    usageContext?: UsageContext[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/EvidenceVariable
export interface EvidenceVariable extends DomainResource {
    resourceType: "EvidenceVariable";

    approvalDate?: string;
    author?: ContactDetail[];
    characteristic: EvidenceVariableCharacteristic[];
    contact?: ContactDetail[];
    copyright?: string;
    date?: string;
    description?: string;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    name?: string;
    note?: Annotation[];
    publisher?: string;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    subtitle?: string;
    title?: string;
    topic?: CodeableConcept[];
    type?: ("dichotomous" | "continuous" | "descriptive");
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isEvidenceVariable = (resource: unknown): resource is EvidenceVariable => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "EvidenceVariable";
}
