// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface GraphDefinitionLink extends BackboneElement {
    description?: string;
    max?: string;
    min?: number;
    path?: string;
    sliceName?: string;
    target?: GraphDefinitionLinkTarget[];
}

export interface GraphDefinitionLinkTarget extends BackboneElement {
    compartment?: GraphDefinitionLinkTargetCompartment[];
    link?: GraphDefinitionLink[];
    params?: string;
    profile?: string;
    type: string;
}

export interface GraphDefinitionLinkTargetCompartment extends BackboneElement {
    code: ("Patient" | "Encounter" | "RelatedPerson" | "Practitioner" | "Device");
    description?: string;
    expression?: string;
    rule: ("identical" | "matching" | "different" | "custom");
    use: ("condition" | "requirement");
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/GraphDefinition
export interface GraphDefinition extends DomainResource {
    resourceType: "GraphDefinition";

    contact?: ContactDetail[];
    date?: string;
    description?: string;
    experimental?: boolean;
    jurisdiction?: CodeableConcept[];
    link?: GraphDefinitionLink[];
    name: string;
    profile?: string;
    publisher?: string;
    purpose?: string;
    start: string;
    status: ("draft" | "active" | "retired" | "unknown");
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isGraphDefinition = (resource: unknown): resource is GraphDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "GraphDefinition";
}
