// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ImmunizationEvaluation
export interface ImmunizationEvaluation extends DomainResource {
    resourceType: "ImmunizationEvaluation";

    authority?: Reference<"Organization">;
    date?: string;
    description?: string;
    doseNumberPositiveInt?: number;
    doseNumberString?: string;
    doseStatus: CodeableConcept;
    doseStatusReason?: CodeableConcept[];
    identifier?: Identifier[];
    immunizationEvent: Reference<"Immunization">;
    patient: Reference<"Patient">;
    series?: string;
    seriesDosesPositiveInt?: number;
    seriesDosesString?: string;
    status: ("completed" | "entered-in-error");
    targetDisease: CodeableConcept;
}
export const isImmunizationEvaluation = (resource: unknown): resource is ImmunizationEvaluation => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ImmunizationEvaluation";
}
