// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { ParameterDefinition } from "../hl7-fhir-r4-core/ParameterDefinition";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { ParameterDefinition } from "../hl7-fhir-r4-core/ParameterDefinition";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Library
export interface Library extends DomainResource {
    resourceType: "Library";

    approvalDate?: string;
    author?: ContactDetail[];
    contact?: ContactDetail[];
    content?: Attachment[];
    copyright?: string;
    dataRequirement?: DataRequirement[];
    date?: string;
    description?: string;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    name?: string;
    parameter?: ParameterDefinition[];
    publisher?: string;
    purpose?: string;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    status: ("draft" | "active" | "retired" | "unknown");
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<"Group">;
    subtitle?: string;
    title?: string;
    topic?: CodeableConcept[];
    type: CodeableConcept;
    url?: string;
    usage?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isLibrary = (resource: unknown): resource is Library => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Library";
}
