// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { Attachment } from "../hl7-fhir-r4-core/Attachment";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { Attachment } from "../hl7-fhir-r4-core/Attachment";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Media
export interface Media extends DomainResource {
    resourceType: "Media";

    basedOn?: Reference<"CarePlan" | "ServiceRequest">[];
    bodySite?: CodeableConcept;
    content: Attachment;
    createdDateTime?: string;
    createdPeriod?: Period;
    device?: Reference<"Device" | "DeviceMetric">;
    deviceName?: string;
    duration?: number;
    encounter?: Reference<"Encounter">;
    frames?: number;
    height?: number;
    identifier?: Identifier[];
    issued?: string;
    modality?: CodeableConcept;
    note?: Annotation[];
    operator?: Reference<"CareTeam" | "Device" | "Organization" | "Patient" | "Practitioner" | "PractitionerRole" | "RelatedPerson">;
    partOf?: Reference<"Resource">[];
    reasonCode?: CodeableConcept[];
    status: ("preparation" | "in-progress" | "not-done" | "on-hold" | "stopped" | "completed" | "entered-in-error" | "unknown");
    subject?: Reference<"Device" | "Group" | "Location" | "Patient" | "Practitioner" | "PractitionerRole" | "Specimen">;
    type?: CodeableConcept;
    view?: CodeableConcept;
    width?: number;
}
export const isMedia = (resource: unknown): resource is Media => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Media";
}
