// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { Coding } from "../hl7-fhir-r4-core/Coding";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Coding } from "../hl7-fhir-r4-core/Coding";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface MessageDefinitionAllowedResponse extends BackboneElement {
    message: string;
    situation?: string;
}

export interface MessageDefinitionFocus extends BackboneElement {
    code: string;
    max?: string;
    min: number;
    profile?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/MessageDefinition
export interface MessageDefinition extends DomainResource {
    resourceType: "MessageDefinition";

    allowedResponse?: MessageDefinitionAllowedResponse[];
    base?: string;
    category?: ("consequence" | "currency" | "notification");
    contact?: ContactDetail[];
    copyright?: string;
    date: string;
    description?: string;
    eventCoding?: Coding;
    eventUri?: string;
    experimental?: boolean;
    focus?: MessageDefinitionFocus[];
    graph?: string[];
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    name?: string;
    parent?: string[];
    publisher?: string;
    purpose?: string;
    replaces?: string[];
    responseRequired?: ("always" | "on-error" | "never" | "on-success");
    status: ("draft" | "active" | "retired" | "unknown");
    title?: string;
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isMessageDefinition = (resource: unknown): resource is MessageDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "MessageDefinition";
}
