// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface NamingSystemUniqueId extends BackboneElement {
    comment?: string;
    period?: Period;
    preferred?: boolean;
    type: ("oid" | "uuid" | "uri" | "other");
    value: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/NamingSystem
export interface NamingSystem extends DomainResource {
    resourceType: "NamingSystem";

    contact?: ContactDetail[];
    date: string;
    description?: string;
    jurisdiction?: CodeableConcept[];
    kind: ("codesystem" | "identifier" | "root");
    name: string;
    publisher?: string;
    responsible?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    type?: CodeableConcept;
    uniqueId: NamingSystemUniqueId[];
    usage?: string;
    useContext?: UsageContext[];
}
export const isNamingSystem = (resource: unknown): resource is NamingSystem => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "NamingSystem";
}
