// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface OperationDefinitionOverload extends BackboneElement {
    comment?: string;
    parameterName?: string[];
}

export interface OperationDefinitionParameter extends BackboneElement {
    binding?: OperationDefinitionParameterBinding;
    documentation?: string;
    max: string;
    min: number;
    name: string;
    part?: OperationDefinitionParameter[];
    referencedFrom?: OperationDefinitionParameterReferencedFrom[];
    searchType?: ("number" | "date" | "string" | "token" | "reference" | "composite" | "quantity" | "uri" | "special");
    targetProfile?: string[];
    type?: string;
    use: ("in" | "out");
}

export interface OperationDefinitionParameterBinding extends BackboneElement {
    strength: ("required" | "extensible" | "preferred" | "example");
    valueSet: string;
}

export interface OperationDefinitionParameterReferencedFrom extends BackboneElement {
    source: string;
    sourceId?: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/OperationDefinition
export interface OperationDefinition extends DomainResource {
    resourceType: "OperationDefinition";

    affectsState?: boolean;
    base?: string;
    code: string;
    comment?: string;
    contact?: ContactDetail[];
    date?: string;
    description?: string;
    experimental?: boolean;
    inputProfile?: string;
    instance: boolean;
    jurisdiction?: CodeableConcept[];
    kind: ("operation" | "query");
    name: string;
    outputProfile?: string;
    overload?: OperationDefinitionOverload[];
    parameter?: OperationDefinitionParameter[];
    publisher?: string;
    purpose?: string;
    resource?: string[];
    status: ("draft" | "active" | "retired" | "unknown");
    system: boolean;
    title?: string;
    type: boolean;
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isOperationDefinition = (resource: unknown): resource is OperationDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "OperationDefinition";
}
