// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Duration } from "../hl7-fhir-r4-core/Duration";
import type { Expression } from "../hl7-fhir-r4-core/Expression";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { Timing } from "../hl7-fhir-r4-core/Timing";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { DataRequirement } from "../hl7-fhir-r4-core/DataRequirement";
export type { Duration } from "../hl7-fhir-r4-core/Duration";
export type { Expression } from "../hl7-fhir-r4-core/Expression";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { Timing } from "../hl7-fhir-r4-core/Timing";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface ResearchElementDefinitionCharacteristic extends BackboneElement {
    definitionCanonical?: string;
    definitionCodeableConcept?: CodeableConcept;
    definitionDataRequirement?: DataRequirement;
    definitionExpression?: Expression;
    exclude?: boolean;
    participantEffectiveDateTime?: string;
    participantEffectiveDescription?: string;
    participantEffectiveDuration?: Duration;
    participantEffectiveGroupMeasure?: ("mean" | "median" | "mean-of-mean" | "mean-of-median" | "median-of-mean" | "median-of-median");
    participantEffectivePeriod?: Period;
    participantEffectiveTimeFromStart?: Duration;
    participantEffectiveTiming?: Timing;
    studyEffectiveDateTime?: string;
    studyEffectiveDescription?: string;
    studyEffectiveDuration?: Duration;
    studyEffectiveGroupMeasure?: ("mean" | "median" | "mean-of-mean" | "mean-of-median" | "median-of-mean" | "median-of-median");
    studyEffectivePeriod?: Period;
    studyEffectiveTimeFromStart?: Duration;
    studyEffectiveTiming?: Timing;
    unitOfMeasure?: CodeableConcept;
    usageContext?: UsageContext[];
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/ResearchElementDefinition
export interface ResearchElementDefinition extends DomainResource {
    resourceType: "ResearchElementDefinition";

    approvalDate?: string;
    author?: ContactDetail[];
    characteristic: ResearchElementDefinitionCharacteristic[];
    comment?: string[];
    contact?: ContactDetail[];
    copyright?: string;
    date?: string;
    description?: string;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    experimental?: boolean;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    library?: string[];
    name?: string;
    publisher?: string;
    purpose?: string;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    shortTitle?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    subjectCodeableConcept?: CodeableConcept;
    subjectReference?: Reference<"Group">;
    subtitle?: string;
    title?: string;
    topic?: CodeableConcept[];
    type: ("population" | "exposure" | "outcome");
    url?: string;
    usage?: string;
    useContext?: UsageContext[];
    variableType?: ("dichotomous" | "continuous" | "descriptive");
    version?: string;
}
export const isResearchElementDefinition = (resource: unknown): resource is ResearchElementDefinition => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "ResearchElementDefinition";
}
