// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { Annotation } from "../hl7-fhir-r4-core/Annotation";
import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Period } from "../hl7-fhir-r4-core/Period";
import type { Reference } from "../hl7-fhir-r4-core/Reference";
import type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { Annotation } from "../hl7-fhir-r4-core/Annotation";
export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Period } from "../hl7-fhir-r4-core/Period";
export type { Reference } from "../hl7-fhir-r4-core/Reference";
export type { RelatedArtifact } from "../hl7-fhir-r4-core/RelatedArtifact";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface RiskEvidenceSynthesisCertainty extends BackboneElement {
    certaintySubcomponent?: RiskEvidenceSynthesisCertaintyCertaintySubcomponent[];
    note?: Annotation[];
    rating?: CodeableConcept[];
}

export interface RiskEvidenceSynthesisCertaintyCertaintySubcomponent extends BackboneElement {
    note?: Annotation[];
    rating?: CodeableConcept[];
    type?: CodeableConcept;
}

export interface RiskEvidenceSynthesisRiskEstimate extends BackboneElement {
    denominatorCount?: number;
    description?: string;
    numeratorCount?: number;
    precisionEstimate?: RiskEvidenceSynthesisRiskEstimatePrecisionEstimate[];
    type?: CodeableConcept;
    unitOfMeasure?: CodeableConcept;
    value?: number;
}

export interface RiskEvidenceSynthesisRiskEstimatePrecisionEstimate extends BackboneElement {
    from?: number;
    level?: number;
    to?: number;
    type?: CodeableConcept;
}

export interface RiskEvidenceSynthesisSampleSize extends BackboneElement {
    description?: string;
    numberOfParticipants?: number;
    numberOfStudies?: number;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/RiskEvidenceSynthesis
export interface RiskEvidenceSynthesis extends DomainResource {
    resourceType: "RiskEvidenceSynthesis";

    approvalDate?: string;
    author?: ContactDetail[];
    certainty?: RiskEvidenceSynthesisCertainty[];
    contact?: ContactDetail[];
    copyright?: string;
    date?: string;
    description?: string;
    editor?: ContactDetail[];
    effectivePeriod?: Period;
    endorser?: ContactDetail[];
    exposure?: Reference<"EvidenceVariable">;
    identifier?: Identifier[];
    jurisdiction?: CodeableConcept[];
    lastReviewDate?: string;
    name?: string;
    note?: Annotation[];
    outcome: Reference<"EvidenceVariable">;
    population: Reference<"EvidenceVariable">;
    publisher?: string;
    relatedArtifact?: RelatedArtifact[];
    reviewer?: ContactDetail[];
    riskEstimate?: RiskEvidenceSynthesisRiskEstimate;
    sampleSize?: RiskEvidenceSynthesisSampleSize;
    status: ("draft" | "active" | "retired" | "unknown");
    studyType?: CodeableConcept;
    synthesisType?: CodeableConcept;
    title?: string;
    topic?: CodeableConcept[];
    url?: string;
    useContext?: UsageContext[];
    version?: string;
}
export const isRiskEvidenceSynthesis = (resource: unknown): resource is RiskEvidenceSynthesis => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "RiskEvidenceSynthesis";
}
