// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export type { BackboneElement } from "../hl7-fhir-r4-core/BackboneElement";
export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { ContactDetail } from "../hl7-fhir-r4-core/ContactDetail";
export type { UsageContext } from "../hl7-fhir-r4-core/UsageContext";

export interface SearchParameterComponent extends BackboneElement {
    definition: string;
    expression: string;
}

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/SearchParameter
export interface SearchParameter extends DomainResource {
    resourceType: "SearchParameter";

    base: string[];
    chain?: string[];
    code: string;
    comparator?: ("eq" | "ne" | "gt" | "lt" | "ge" | "le" | "sa" | "eb" | "ap")[];
    component?: SearchParameterComponent[];
    contact?: ContactDetail[];
    date?: string;
    derivedFrom?: string;
    description: string;
    experimental?: boolean;
    expression?: string;
    jurisdiction?: CodeableConcept[];
    modifier?: ("missing" | "exact" | "contains" | "not" | "text" | "in" | "not-in" | "below" | "above" | "type" | "identifier" | "ofType")[];
    multipleAnd?: boolean;
    multipleOr?: boolean;
    name: string;
    publisher?: string;
    purpose?: string;
    status: ("draft" | "active" | "retired" | "unknown");
    target?: string[];
    type: ("number" | "date" | "string" | "token" | "reference" | "composite" | "quantity" | "uri" | "special");
    url: string;
    useContext?: UsageContext[];
    version?: string;
    xpath?: string;
    xpathUsage?: ("normal" | "phonetic" | "nearby" | "distance" | "other");
}
export const isSearchParameter = (resource: unknown): resource is SearchParameter => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "SearchParameter";
}
