// WARNING: This file is autogenerated by @atomic-ehr/codegen.
// GitHub: https://github.com/atomic-ehr/codegen
// Any manual changes made to this file may be overwritten.

import type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
import type { DomainResource } from "../hl7-fhir-r4-core/DomainResource";
import type { Identifier } from "../hl7-fhir-r4-core/Identifier";
import type { Reference } from "../hl7-fhir-r4-core/Reference";

export type { CodeableConcept } from "../hl7-fhir-r4-core/CodeableConcept";
export type { Identifier } from "../hl7-fhir-r4-core/Identifier";
export type { Reference } from "../hl7-fhir-r4-core/Reference";

// CanonicalURL: http://hl7.org/fhir/StructureDefinition/Slot
export interface Slot extends DomainResource {
    resourceType: "Slot";

    appointmentType?: CodeableConcept;
    comment?: string;
    end: string;
    identifier?: Identifier[];
    overbooked?: boolean;
    schedule: Reference<"Schedule">;
    serviceCategory?: CodeableConcept[];
    serviceType?: CodeableConcept[];
    specialty?: CodeableConcept[];
    start: string;
    status: ("busy" | "free" | "busy-unavailable" | "busy-tentative" | "entered-in-error");
}
export const isSlot = (resource: unknown): resource is Slot => {
    return resource !== null && typeof resource === "object" && (resource as {resourceType: string}).resourceType === "Slot";
}
